//get the big object from 

const parksListObj = {
    abli: "Abraham Lincoln Birthplace National Historical Park",
    acad: "Acadia National Park",
    adam: "Adams National Historical Park",
    afam: "African American Civil War Memorial",
    afbg: "African Burial Ground National Monument",
    agfo: "Agate Fossil Beds National Monument",
    alag: "Alagnak Wild River",
    alca: "Alcatraz Island",
    aleu: "Aleutian Islands World War II National Historic Area",
    alfl: "Alibates Flint Quarries National Monument",
    alka: "Ala Kahakai National Historic Trail",
    alpo: "Allegheny Portage Railroad National Historic Site",
    amis: "Amistad National Recreation Area",
    amme: "American Memorial Park",
    anac: "Anacostia Park",
    anch: "Alaska Public Lands",
    ande: "Andersonville National Historic Site",
    ania: "Aniakchak National Monument & Preserve",
    anjo: "Andrew Johnson National Historic Site",
    anti: "Antietam National Battlefield",
    apco: "Appomattox Court House National Historical Park",
    apis: "Apostle Islands National Lakeshore",
    appa: "Appalachian National Scenic Trail",
    arch: "Arches National Park",
    arho: "Arlington House, The Robert  E. Lee Memorial",
    armo: "Arabia Mountain National Heritage Area",
    arpo: "Arkansas Post National Memorial",
    asis: "Assateague Island National Seashore",
    attr: "Atchafalaya National Heritage Area",
    auca: "Augusta Canal National Heritage Area",
    auto: "Motor Cities National Heritage Area",
    avia: "National Aviation Heritage Area",
    azru: "Aztec Ruins National Monument",
    badl: "Badlands National Park",
    balt: "Baltimore National Heritage Area",
    band: "Bandelier National Monument",
    bawa: "Baltimore-Washington Parkway",
    bela: "Bering Land Bridge National Preserve",
    beol: "Bent's Old Fort National Historic Site",
    bepa: "Belmont-Paul Women's Equality National Monument",
    bibe: "Big Bend National Park",
    bica: "Bighorn Canyon National Recreation Area",
    bicr: "Birmingham Civil Rights National Monument",
    bicy: "Big Cypress National Preserve",
    biho: "Big Hole National Battlefield",
    bisc: "Biscayne National Park",
    biso: "Big South Fork National River & Recreation Area",
    bith: "Big Thicket National Preserve",
    blac: "John H. Chafee Blackstone River Valley National Heritage Corridor",
    blca: "Black Canyon Of The Gunnison National Park",
    blri: "Blue Ridge Parkway",
    blrn: "Blue Ridge National Heritage Area",
    blrv: "Blackstone River Valley National Historical Park",
    blue: "Bluestone National Scenic River",
    boaf: "Boston African American National Historic Site",
    boha: "Boston Harbor Islands National Recreation Area",
    bost: "Boston National Historical Park",
    bowa: "Booker T Washington National Monument",
    brca: "Bryce Canyon National Park",
    brcr: "Brices Cross Roads National Battlefield Site",
    brvb: "Brown v. Board of Education National Historic Site",
    buff: "Buffalo National River",
    buis: "Buck Island Reef National Monument",
    cabr: "Cabrillo National Monument",
    cach: "Canyon de Chelly National Monument",
    cacl: "Castle Clinton National Monument",
    caco: "Cape Cod National Seashore",
    cagr: "Casa Grande Ruins National Monument",
    caha: "Cape Hatteras National Seashore",
    cahi: "Capitol Hill Parks",
    cajo: "Captain John Smith Chesapeake National Historic Trail",
    cakr: "Cape Krusenstern National Monument",
    cali: "California National Historic Trail",
    calo: "Cape Lookout National Seashore",
    came: "Cape Henry Memorial Part of Colonial National Historical Park",
    camo: "Castle Mountains National Monument",
    cana: "Canaveral National Seashore",
    cane: "Camp Nelson National Monument",
    cany: "Canyonlands National Park",
    care: "Capitol Reef National Park",
    cari: "Cane River Creole National Historical Park",
    carl: "Carl Sandburg Home National Historic Site",
    casa: "Castillo de San Marcos National Monument",
    cato: "Catoctin Mountain Park",
    cave: "Carlsbad Caverns National Park",
    cavo: "Capulin Volcano National Monument",
    cawo: "Carter G. Woodson Home National Historic Site",
    cbgn: "Chesapeake Bay Gateways and Watertrails Network",
    cbpo: "Chesapeake Bay",
    cebe: "Cedar Creek & Belle Grove National Historical Park",
    cebr: "Cedar Breaks National Monument",
    cech: "César E. Chávez National Monument",
    cham: "Chamizal National Memorial",
    chat: "Chattahoochee River National Recreation Area",
    chch: "Chickamauga & Chattanooga National Military Park",
    chcu: "Chaco Culture National Historical Park",
    chic: "Chickasaw National Recreation Area",
    chir: "Chiricahua National Monument",
    chis: "Channel Islands National Park",
    choh: "Chesapeake & Ohio Canal National Historical Park",
    chpi: "Charles Pinckney National Historic Site",
    chri: "Christiansted National Historic Site",
    chsc: "Little Rock Central High School National Historic Site",
    chva: "Champlain Valley National Heritage Partnership",
    chyo: "Charles Young Buffalo Soldiers National Monument",
    ciro: "City Of Rocks National Reserve",
    clba: "Clara Barton National Historic Site",
    coal: "Coal National Heritage Area",
    coga: "Constitution Gardens",
    colm: "Colorado National Monument",
    colo: "Colonial National Historical Park",
    colt: "Coltsville National Historical Park",
    cong: "Congaree National Park",
    coro: "Coronado National Memorial",
    cowp: "Cowpens National Battlefield",
    crha: "Cane River National Heritage Area",
    crla: "Crater Lake National Park",
    crmo: "Craters Of The Moon National Monument & Preserve",
    cuga: "Cumberland Gap National Historical Park",
    cuis: "Cumberland Island National Seashore",
    cure: "Curecanti National Recreation Area",
    cuva: "Cuyahoga Valley National Park",
    cwdw: "Civil War Defenses of Washington",
    daav: "Dayton Aviation Heritage National Historical Park",
    dabe: "David Berger National Memorial",
    dele: "Delaware & Lehigh National Heritage Corridor",
    dena: "Denali National Park & Preserve",
    depo: "Devils Postpile National Monument",
    deso: "De Soto National Memorial",
    deto: "Devils Tower National Monument",
    deva: "Death Valley National Park",
    dewa: "Delaware Water Gap National Recreation Area",
    dino: "Dinosaur National Monument",
    drto: "Dry Tortugas National Park",
    ebla: "Ebey's Landing National Historical Reserve",
    edal: "Edgar Allan Poe National Historic Site",
    edis: "Thomas Edison National Historical Park",
    efmo: "Effigy Mounds National Monument",
    eise: "Eisenhower National Historic Site",
    elca: "El Camino Real de Tierra Adentro National Historic Trail",
    elis: "Ellis Island Part of Statue of Liberty National Monument",
    elma: "El Malpais National Monument",
    elmo: "El Morro National Monument",
    elro: "Eleanor Roosevelt National Historic Site",
    elte: "El Camino Real de los Tejas National Historic Trail",
    erie: "Erie Canalway National Heritage Corridor",
    esse: "Essex National Heritage Area",
    euon: "Eugene O'Neill National Historic Site",
    ever: "Everglades National Park",
    fati: "Fallen Timbers Battlefield and Fort Miamis National Historic Site",
    feha: "Federal Hall National Memorial",
    fiis: "Fire Island National Seashore",
    fila: "First Ladies National Historic Site",
    flfo: "Florissant Fossil Beds National Monument",
    flni: "Flight 93 National Memorial",
    fobo: "Fort Bowie National Historic Site",
    fobu: "Fossil Butte National Monument",
    foda: "Fort Davis National Historic Site",
    fodo: "Fort Donelson National Battlefield",
    fodu: "Fort Dupont Park",
    fofo: "Fort Foote Park",
    fofr: "Fort Frederica National Monument",
    fola: "Fort Laramie National Historic Site",
    fols: "Fort Larned National Historic Site",
    foma: "Fort Matanzas National Monument",
    fomc: "Fort McHenry National Monument and Historic Shrine",
    fomr: "Fort Monroe National Monument",
    fone: "Fort Necessity National Battlefield",
    fopo: "Fort Point National Historic Site",
    fopu: "Fort Pulaski National Monument",
    fora: "Fort Raleigh National Historic Site",
    fosc: "Fort Scott National Historic Site",
    fosm: "Fort Smith National Historic Site",
    fost: "Fort Stanwix National Monument",
    fosu: "Fort Sumter and Fort Moultrie National Historical Park",
    foth: "Ford's Theatre",
    foun: "Fort Union National Monument",
    fous: "Fort Union Trading Post National Historic Site",
    fova: "Fort Vancouver National Historic Site",
    fowa: "Fort Washington Park",
    frde: "Franklin Delano Roosevelt Memorial",
    frdo: "Frederick Douglass National Historic Site",
    frhi: "Friendship Hill National Historic Site",
    frla: "Frederick Law Olmsted National Historic Site",
    frri: "Freedom Riders National Monument",
    frsp: "Fredericksburg & Spotsylvania National Military Park",
    frst: "First State National Historical Park",
    gaar: "Gates Of The Arctic National Park & Preserve",
    gari: "Gauley River National Recreation Area",
    gate: "Gateway National Recreation Area",
    gegr: "General Grant National Memorial",
    gero: "George Rogers Clark National Historical Park",
    gett: "Gettysburg National Military Park",
    gewa: "George Washington Birthplace National Monument",
    gicl: "Gila Cliff Dwellings National Monument",
    glac: "Glacier National Park",
    glba: "Glacier Bay National Park & Preserve",
    glca: "Glen Canyon National Recreation Area",
    glde: "Gloria Dei Church National Historic Site",
    glec: "Glen Echo Park",
    goga: "Golden Gate National Recreation Area",
    gois: "Governors Island National Monument",
    gosp: "Golden Spike National Historical Park",
    grba: "Great Basin National Park",
    grca: "Grand Canyon National Park",
    gree: "Greenbelt Park",
    greg: "Great Egg Harbor River",
    grfa: "Great Falls Park",
    grko: "Grant-Kohrs Ranch National Historic Site",
    grpo: "Grand Portage National Monument",
    grsa: "Great Sand Dunes National Park & Preserve",
    grsm: "Great Smoky Mountains National Park",
    grsp: "Green Springs",
    grte: "Grand Teton National Park",
    guco: "Guilford Courthouse National Military Park",
    guge: "Gullah/Geechee Cultural Heritage Corridor",
    guis: "Gulf Islands National Seashore",
    gumo: "Guadalupe Mountains National Park",
    gwca: "George Washington Carver National Monument",
    gwmp: "George Washington Memorial Parkway",
    hafe: "Harpers Ferry National Historical Park",
    hafo: "Hagerman Fossil Beds National Monument",
    hagr: "Hamilton Grange National Memorial",
    haha: "Harmony Hall",
    hale: "Haleakal&#257; National Park",
    hamp: "Hampton National Historic Site",
    hart: "Harriet Tubman National Historical Park",
    hatu: "Harriet Tubman Underground Railroad National Historical Park",
    havo: "Hawai'i Volcanoes National Park",
    heho: "Herbert Hoover National Historic Site",
    hobe: "Horseshoe Bend National Military Park",
    hocu: "Hopewell Culture National Historical Park",
    hofr: "Home Of Franklin D Roosevelt National Historic Site",
    hofu: "Hopewell Furnace National Historic Site",
    home: "Homestead National Monument of America",
    hono: "Honouliuli National Historic Site",
    hosp: "Hot Springs National Park",
    hove: "Hovenweep National Monument",
    hstr: "Harry S Truman National Historic Site",
    hurv: "Hudson River Valley National Heritage Area",
    hutr: "Hubbell Trading Post National Historic Site",
    iafl: "Ice Age Floods National Geologic Trail",
    iatr: "Ice Age National Scenic Trail",
    inde: "Independence National Historical Park",
    indu: "Indiana Dunes National Park",
    inup: "I&#241;upiat Heritage Center",
    isro: "Isle Royale National Park",
    jaga: "James A Garfield National Historic Site",
    jame: "Historic Jamestowne Part of Colonial National Historical Park",
    jazz: "New Orleans Jazz National Historical Park",
    jeca: "Jewel Cave National Monument",
    jeff: "Gateway Arch National Park",
    jela: "Jean Lafitte National Historical Park and Preserve",
    jica: "Jimmy Carter National Historic Site",
    joda: "John Day Fossil Beds National Monument",
    jofi: "John Fitzgerald Kennedy National Historic Site",
    jofl: "Johnstown Flood National Memorial",
    jomu: "John Muir National Historic Site",
    jotr: "Joshua Tree National Park",
    jthg: "Journey Through Hallowed Ground National Heritage Area",
    juba: "Juan Bautista de Anza National Historic Trail",
    kaho: "Kaloko-Honok&#333;hau National Historical Park",
    kala: "Kalaupapa National Historical Park",
    katm: "Katmai National Park & Preserve",
    kaww: "Katahdin Woods and Waters National Monument",
    keaq: "Kenilworth Park & Aquatic Gardens",
    kefj: "Kenai Fjords National Park",
    kemo: "Kennesaw Mountain National Battlefield Park",
    kewe: "Keweenaw National Historical Park",
    kimo: "Kings Mountain National Military Park",
    klgo: "Klondike Gold Rush National Historical Park",
    klse: "Klondike Gold Rush - Seattle Unit National Historical Park",
    knri: "Knife River Indian Villages National Historic Site",
    kova: "Kobuk Valley National Park",
    kowa: "Korean War Veterans Memorial",
    labe: "Lava Beds National Monument",
    lacl: "Lake Clark National Park & Preserve",
    lake: "Lake Mead National Recreation Area",
    lamr: "Lake Meredith National Recreation Area",
    laro: "Lake Roosevelt National Recreation Area",
    lavo: "Lassen Volcanic National Park",
    lecl: "Lewis & Clark National Historic Trail",
    lewi: "Lewis and Clark National Historical Park",
    libi: "Little Bighorn Battlefield National Monument",
    libo: "Lincoln Boyhood National Memorial",
    liho: "Lincoln Home National Historic Site",
    linc: "Lincoln Memorial",
    liri: "Little River Canyon National Preserve",
    lode: "Lower Delaware National Wild and Scenic River",
    loea: "Lower East Side Tenement Museum National Historic Site",
    long: "Longfellow House Washington's Headquarters National Historic Site",
    lowe: "Lowell National Historical Park",
    lyba: "LBJ Memorial Grove on the Potomac",
    lyjo: "Lyndon B Johnson National Historical Park",
    maac: "Maine Acadian Culture",
    mabi: "Marsh - Billings - Rockefeller National Historical Park",
    maca: "Mammoth Cave National Park",
    malu: "Martin Luther King, Jr. National Historical Park",
    mamc: "Mary McLeod Bethune Council House National Historic Site",
    mana: "Manassas National Battlefield Park",
    manz: "Manzanar National Historic Site",
    mapr: "Manhattan Project National Historical Park",
    mava: "Martin Van Buren National Historic Site",
    mawa: "Maggie L Walker National Historic Site",
    meve: "Mesa Verde National Park",
    mide: "Mississippi Delta National Heritage Area",
    migu: "Mississippi Gulf National Heritage Area",
    mihi: "Mississippi Hills National Heritage Area",
    miin: "Minidoka National Historic Site",
    mima: "Minute Man National Historical Park",
    mimi: "Minuteman Missile National Historic Site",
    miss: "Mississippi National River and Recreation Area",
    mlkm: "Martin Luther King, Jr. Memorial",
    mnrr: "Missouri National Recreational River",
    moca: "Montezuma Castle National Monument",
    mocr: "Moores Creek National Battlefield",
    moja: "Mojave National Preserve",
    mono: "Monocacy National Battlefield",
    mopi: "Mormon Pioneer National Historic Trail",
    mora: "Mount Rainier National Park",
    morr: "Morristown National Historical Park",
    moru: "Mount Rushmore National Memorial",
    mush: "Muscle Shoals National Heritage Area",
    muwo: "Muir Woods National Monument",
    nabr: "Natural Bridges National Monument",
    nace: "National Capital Parks-East",
    nama: "National Mall and Memorial Parks",
    natc: "Natchez National Historical Park",
    natr: "Natchez Trace Parkway",
    natt: "Natchez Trace National Scenic Trail",
    nava: "Navajo National Monument",
    nebe: "New Bedford Whaling National Historical Park",
    neen: "New England National Scenic Trail",
    nepe: "Nez Perce National Historical Park",
    neri: "New River Gorge National River",
    nico: "Nicodemus National Historic Site",
    nifa: "Niagara Falls National Heritage Area",
    niob: "Niobrara National Scenic River",
    nisi: "Ninety Six National Historic Site",
    noat: "Noatak National Preserve",
    noca: "North Cascades National Park",
    noco: "North Country National Scenic Trail",
    npnh: "National Parks of New York Harbor",
    npsa: "National Park of American Samoa",
    obed: "Obed Wild & Scenic River",
    ocmu: "Ocmulgee Mounds National Historical Park",
    oire: "Oil Region National Heritage Area",
    okci: "Oklahoma City National Memorial",
    olsp: "Old Spanish National Historic Trail",
    olym: "Olympic National Park",
    orca: "Oregon Caves National Monument & Preserve",
    oreg: "Oregon National Historic Trail",
    orpi: "Organ Pipe Cactus National Monument",
    ovvi: "Overmountain Victory National Historic Trail",
    oxhi: "Oxon Cove  Park & Oxon Hill Farm",
    ozar: "Ozark National Scenic Riverways",
    paal: "Palo Alto Battlefield National Historical Park",
    paav: "Pennsylvania Avenue",
    pagr: "Paterson Great Falls National Historical Park",
    pais: "Padre Island National Seashore",
    para: "Parashant National Monument",
    peco: "Pecos National Historical Park",
    pefo: "Petrified Forest National Park",
    peri: "Pea Ridge National Military Park",
    pete: "Petersburg National Battlefield",
    petr: "Petroglyph National Monument",
    pevi: "Perry's Victory & International Peace Memorial",
    pima: "Hohokam Pima National Monument",
    pine: "New Jersey Pinelands National Reserve",
    pinn: "Pinnacles National Park",
    pipe: "Pipestone National Monument",
    piro: "Pictured Rocks National Lakeshore",
    pisc: "Piscataway Park",
    pisp: "Pipe Spring National Monument",
    poch: "Port Chicago Naval Magazine National Memorial",
    poex: "Pony Express National Historic Trail",
    pohe: "Potomac Heritage National Scenic Trail",
    popo: "Poverty Point National Monument",
    pore: "Point Reyes National Seashore",
    prsf: "Presidio of San Francisco",
    prwi: "Prince William Forest Park",
    puhe: "Pu`ukohol&#257; Heiau National Historic Site",
    puho: "Pu`uhonua O H&#333;naunau National Historical Park",
    pull: "Pullman National Monument",
    qush: "The Last Green Valley National Heritage Corridor",
    rabr: "Rainbow Bridge National Monument",
    redw: "Redwood National and State Parks",
    reer: "Reconstruction Era National Historical Park",
    rich: "Richmond National Battlefield Park",
    rigr: "Rio Grande Wild & Scenic River",
    rira: "River Raisin National Battlefield Park",
    rist: "Rivers Of Steel National Heritage Area",
    roca: "Roosevelt Campobello International Park",
    rocr: "Rock Creek Park",
    romo: "Rocky Mountain National Park",
    rori: "Rosie the Riveter WWII Home Front National Historical Park",
    rowi: "Roger Williams National Memorial",
    ruca: "Russell Cave National Monument",
    saan: "San Antonio Missions National Historical Park",
    sacn: "Saint Croix National Scenic Riverway",
    sacr: "Saint Croix Island International Historic Site",
    safe: "Santa Fe National Historic Trail",
    safr: "San Francisco Maritime National Historical Park",
    saga: "Saint-Gaudens National Historical Park",
    sagu: "Saguaro National Park",
    sahi: "Sagamore Hill National Historic Site",
    sair: "Saugus Iron Works National Historic Site",
    sajh: "San Juan Island National Historical Park",
    saju: "San Juan National Historic Site",
    sama: "Salem Maritime National Historic Site",
    samo: "Santa Monica Mountains National Recreation Area",
    sand: "Sand Creek Massacre National Historic Site",
    sapa: "Saint Paul's Church National Historic Site",
    sapu: "Salinas Pueblo Missions National Monument",
    sara: "Saratoga National Historical Park",
    sari: "Salt River Bay National Historical Park and Ecological Preserve",
    scbl: "Scotts Bluff National Monument",
    scrv: "Schuylkill River Valley National Heritage Area",
    seki: "Sequoia & Kings Canyon National Parks",
    semo: "Selma To Montgomery National Historic Trail",
    shen: "Shenandoah National Park",
    shil: "Shiloh National Military Park",
    shvb: "Shenandoah Valley Battlefields National Historic District",
    sitk: "Sitka National Historical Park",
    slbe: "Sleeping Bear Dunes National Lakeshore",
    soca: "South Carolina National Heritage Corridor",
    spar: "Springfield Armory National Historic Site",
    stea: "Steamtown National Historic Site",
    stli: "Statue Of Liberty National Monument",
    ston: "Stonewall National Monument",
    stri: "Stones River National Battlefield",
    stsp: "Star-Spangled Banner National Historic Trail",
    sucr: "Sunset Crater Volcano National Monument",
    tapr: "Tallgrass Prairie National Preserve",
    tecw: "Tennessee Civil War National Heritage Area",
    thco: "Thomas Cole National Historic Site",
    this: "Theodore Roosevelt Island",
    thje: "Thomas Jefferson Memorial",
    thko: "Thaddeus Kosciuszko National Memorial",
    thrb: "Theodore Roosevelt Birthplace National Historic Site",
    thri: "Theodore Roosevelt Inaugural National Historic Site",
    thro: "Theodore Roosevelt National Park",
    thst: "Thomas Stone National Historic Site",
    tica: "Timpanogos Cave National Monument",
    timu: "Timucuan Ecological & Historic Preserve",
    tont: "Tonto National Monument",
    tosy: "Touro Synagogue National Historic Site",
    trte: "Trail Of Tears National Historic Trail",
    tuai: "Tuskegee Airmen National Historic Site",
    tuin: "Tuskegee Institute National Historic Site",
    tule: "Tule Lake National Monument",
    tuma: "Tumacácori National Historical Park",
    tupe: "Tupelo National Battlefield",
    tusk: "Tule Springs Fossil Beds National Monument",
    tuzi: "Tuzigoot National Monument",
    ulsg: "Ulysses S Grant National Historic Site",
    upde: "Upper Delaware Scenic & Recreational River",
    vafo: "Valley Forge National Historical Park",
    vall: "Valles Caldera National Preserve",
    valr: "Pearl Harbor National Memorial",
    vama: "Vanderbilt Mansion National Historic Site",
    vick: "Vicksburg National Military Park",
    vicr: "Virgin Islands Coral Reef National Monument",
    viis: "Virgin Islands National Park",
    vive: "Vietnam Veterans Memorial",
    voya: "Voyageurs National Park",
    waba: "Washita Battlefield National Historic Site",
    waca: "Walnut Canyon National Monument",
    waco: "Waco Mammoth National Monument",
    wamo: "Washington Monument",
    wapa: "War In The Pacific National Historical Park",
    waro: "Washington-Rochambeau National Historic Trail",
    wefa: "Weir Farm National Historic Site",
    whee: "Wheeling National Heritage Area",
    whho: "President's Park (White House)",
    whis: "Whiskeytown National Recreation Area",
    whmi: "Whitman Mission National Historic Site",
    whsa: "White Sands National Monument",
    wica: "Wind Cave National Park",
    wicl: "President William Jefferson Clinton Birthplace Home National Historic Site",
    wicr: "Wilson's Creek National Battlefield",
    wiho: "William Howard Taft National Historic Site",
    wing: "Wing Luke Museum Affiliated Area",
    wori: "Women's Rights National Historical Park",
    wotr: "Wolf Trap National Park for the Performing Arts",
    wrbr: "Wright Brothers National Memorial",
    wrst: "Wrangell - St Elias National Park & Preserve",
    wupa: "Wupatki National Monument",
    wwii: "World War II Memorial",
    xrds: "Crossroads of the American Revolution National Heritage Area",
    yell: "Yellowstone National Park",
    york: "Yorktown Battlefield Part of Colonial National Historical Park",
    yose: "Yosemite National Park",
    yuch: "Yukon - Charley Rivers National Preserve",
    yuho: "Yucca House National Monument",
    zion: "Zion National Park"
}

const parkNames = Object.values(parksListObj).sort();








// function reduceResponse(responseJson) {
//     console.log(responseJson);
//     console.log(parksListObj);
//     console.log(parkNames);
    // let stateCodes = [];
    // //console.log(stateCodes);
    // console.log(responseJson);
    // for (let i = 0; i < responseJson.data.length; i++) {
    //     stateCodes.push(responseJson.data[i].fullName);
    // }

    // //sort array alphabetically
    // stateCodes.sort();
    // console.log(stateCodes);
//}





// function reduceResponse(responseJson) {
//     let stateCodes = new Object();
//     //console.log(stateCodes);
//     console.log(responseJson);
//     for (let i = 0; i < responseJson.data.length; i++) {
//         stateCodes[responseJson.data[i].parkCode] = responseJson.data[i].fullName;
//     }
//     console.log(stateCodes);
// }